export const LABEL = {
    DOCUMENT_SEARCH: 'Document Search',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    SIGN_IN: 'Sign In',
    CREATE_ACCOUNT: 'Create Account',
    FULL_NAME: 'Full Name',
    EMAIL: 'Email',
    SIGN_UP: 'Sign Up',
    PARSE: 'Parse Document',
    REJECT: 'Reject Indexing',
    INDEX: 'Index Document',
    LOW_CLASSIFICATION: 'Low',
    MEDIUM_CLASSIFICATION: 'Medium',
    HIGH_CLASSIFICATION: 'High',
    CRITICAL_CLASSIFICATION: 'Critical',
    FORENSIC_NAME: 'Forensic Analyst Name',
    ORGANIZATION: 'Organization Name',
    ADDRESS: 'Address',
    MALWARE_NAME: 'Threat Name',
    HASH: 'Hash',
    CLASSIFICATION: 'Clasification',
    BEHAVIOR_DESCRIPTION: 'Behavior Description',
    NOTHING_HERE_TITLE: 'Nothing here yet',
    NOTHING_HERE_DESCRIPTION: 'Search the indexed reports and review results on this page.',
    SEARCH: 'Search',
    SEARCH_DOCUMENTS: 'Search Documents',
    NEW_SEARCH: 'New Search',
    PREV: 'Prev',
    NEXT: 'Next',
    PAGE: 'Page ',
    OF: ' of ',
    TOTAL_RESULTS: ' total results',
    ANALYST_HASH_CLASS_TITLE: 'Analyst, Hash & Classification',
    ANALYST_HASH_CLASS_HINT: 'Find reports by forensic analyst, hash value, and threat classification.',
    ORG_THREAT_TITLE: 'Organization & Threat Name',
    ORG_THREAT_HINT: 'Search by CERT/CSIRT organization and analyzed malware/threat name.',
    KNN_FREE_TEXT_TITLE: 'Semantic Search (KNN)',
    KNN_FREE_TEXT_HINT: 'Approximate nearest-neighbor search using a free-text query.',
    FULLTEXT_PDF_TITLE: 'Report Description (Full-text)',
    FULLTEXT_PDF_HINT: 'Search within the report text extracted from the PDF.',
    BOOLEAN_SEMI_STRUCTURED_TITLE: 'Advanced Boolean Search',
    BOOLEAN_SEMI_STRUCTURED_HINT: 'Combine conditions with AND / OR / NOT, with C-like operator precedence.',
    TEXT: 'Text',
    DOCUMENT_DETAILS: 'Document Details',
    QUERY: 'Query'
}
