#If there is no .env file in the resources directory, comment out the line below
spring.config.import=optional:classpath:.env[.properties]
spring.application.name=back

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#JWT
jwt.secret=${JWT_SECRET_KEY}