export const SEVERITY = {
    ERROR: 'error',
    SUCCESS: 'success',
    WARNING: 'warning',
    INFO: 'info'
}

export const SEARCH_PAGE = {
    ANALYST_HASH_CLASS: 'ANALYST_HASH_CLASS',
    ORG_THREAT: 'ORG_THREAT',
    KNN_FREE_TEXT: 'KNN_FREE_TEXT',
    FULLTEXT_PDF: 'FULLTEXT_PDF',
    BOOLEAN_SEMI_STRUCTURED: 'BOOLEAN_SEMI_STRUCTURED'
}