import Head from "next/head"
import { useEffect, useState } from "react";
import { DialogWithHeader } from "@/components/widgets/Dialog"

export default function Home() {
  
  const [openDialog, setOpenDialog] = useState(false)

  function onSoldierClick(soldier) {
        setOpenDialog(true)
    }

    function onAddClick() {
        setOpenDialog(true)
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => setOpenDialog(true)}>
          Dialog
        </button>

        <DialogWithHeader
          isOpen={openDialog}
          width={600}
          onCloseModal={() => setOpenDialog(false)}
          title="Dialog Title">
            Lorem Ipsum
        </DialogWithHeader>
      </main>
    </>
  );
}
