import Head from "next/head"
import style from "../styles/Search.module.css"
import { Button } from "@mui/material";
import formStyle from "../styles/Form.module.css"
import { DialogWithHeader } from "@/components/widgets/Dialog";
import { useState } from "react";
import { LABEL } from "@/values/Labels";
import SearchForm from "@/components/feature/SearchForm";

export default function Home() {

    const [openSearchDialog, setOpenSearchDialog] = useState(false)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={style.page}>
                <div className={style.descriptionWrapper}>
                    <div className={style.descriptionTitle}>{LABEL.NOTHING_HERE_TITLE}</div>

                    <div className="spacer-h-s"/>

                    <div>{LABEL.NOTHING_HERE_DESCRIPTION}</div>

                    <div className="spacer-h-l"/>

                    <Button
                        className={`${formStyle.button} ${formStyle.raisedButton} ${style.descriptionButton}`}
                        disableRipple
                        onClick={() => setOpenSearchDialog(true)} >
                        {LABEL.SEARCH}
                    </Button>
                </div>

                 <DialogWithHeader
                      isOpen={openSearchDialog}
                      width={900}
                      onCloseModal={() => setOpenSearchDialog(false)}
                      title={LABEL.SEARCH_DOCUMENTS} >
                      <SearchForm />
                  </DialogWithHeader>
                
            </main>
        </>
    );
}
